


//Dialog Box indentification IDs


#define DID_EXIT    3
#define DID_SET    4

/****************************************************************************
****************************************************************************/
#define IDD_PORT_SELECT           	500

#define IDC_COMM1_SELECT             510
#define IDC_COMM2_SELECT             511
#define IDC_COMM3_SELECT             512
#define IDC_COMM4_SELECT             513

/****************************************************************************
****************************************************************************/
#define IDD_PORT_INIT               600

#define IDC_PARITY_NO                620
#define IDC_PARITY_ODD               621
#define IDC_PARITY_EVEN              622
#define IDC_PARITY_MARK              623
#define IDC_PARITY_SPACE             624

#define IDC_STOP_BIT1                630
#define IDC_STOP_BIT1_5              631
#define IDC_STOP_BIT2                632

#define IDC_DATA_BIT5                640
#define IDC_DATA_BIT6                641
#define IDC_DATA_BIT7                642
#define IDC_DATA_BIT8                643

#define IDC_SET_BIT_RATE             650


/****************************************************************************
****************************************************************************/
#define IDD_SLIDER_CONTROL               700


#define IDC_SLIDER_CONTROL                710
#define IDC_MID_POINT                     711
#define IDC_SLIDER_DATA                   712



/****************************************************************************
                      S T R I N G    T A B L E   I D S
****************************************************************************/


#define IDS_CLIENT1CLASS            1

/****************************************************************************
                      M E S S A G E   T A B L E   I D S
****************************************************************************/


#define IDMSG_INITFAILED                1
#define IDMSG_TEST                     2
#define IDMSG_CANNOTLOADEXITLIST       3
#define IDMSG_WINDLGFLAGS1             4
#define IDMSG_NOCOMMPORTSELECTED       5

                                            

#define IDR_WIN1_ICON  1

/****************************************************************************
                  Menu item IDs
****************************************************************************/
#define IDR_MAIN_MENU_WIN1       1
#define IDM_PORT_SELECTION       1000
#define IDM_PORT_INIT            1001
#define IDM_SLIDER_CONTROL       1002
#define IDM_DCB                  1500 
#define WM_TERMINAL_MSG          WM_USER+100
#define TMID_QUERY_TIMER         WM_USER+101
#define MESSAGELEN               50    /* maximum length for messages */
#define IDD_MSGBOX               10


